version: '3'
services:
  master:
    build:
      context: ./master
    ports:
      - "8888:8080"
    volumes:
      - master-home:/var/jenkins_home

  golang:
    build:
      context: ./slave-golang
    deploy:
      replicas: 4
    environment:
      MASTER: 'http://master:8080'
      USERNAME: 'admin'
      PASSWORD: 'passw0rd'
      LABELS: 'golang'
      EXECUTORS: '1'
    privileged: true
  java:
    build:
      context: ./slave-java
    deploy:
      replicas: 4
    environment:
      MASTER: 'http://master:8080'
      USERNAME: 'admin'
      PASSWORD: 'passw0rd'
      LABELS: 'java'
      EXECUTORS: '1'
    privileged: true
  nodejs:
    build:
      context: ./slave-nodejs
    deploy:
      replicas: 6
    environment:
      MASTER: 'http://master:8080'
      USERNAME: 'admin'
      PASSWORD: 'passw0rd'
      LABELS: 'nodejs'
      EXECUTORS: '1'
    privileged: true

volumes:
  master-home: